[package]
name = "wave_framework"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.18" # egui framework
log = "0.4"
xml-rs = "0.8"
